<?xml version="1.0"?>
<package format="3">
  <name>multi_sensor_calibration</name>
  <version>0.1.0</version>
  <description>Offline temporal, intrinsic, and extrinsic calibration tools for ROS 2 sensor bags.</description>
  <maintainer email="carbuncle01@users.noreply.github.com">carbuncle01</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>event_camera_py</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
